<?php

use Illuminate\Database\Seeder;

class CarModelCarTypeTableSeeder extends Seeder
{
    public function run()
    {
        $model_types = [
            [
                'car_model_id' => '1',
                'car_type_id' => '1',
                'preview' => true,
                'price' => 550900,
                'special_price' => 550900,
                'credit_from' => 5079,
                'count'=>0,
                'image' => '/images/slider/mini/granta/mobile/lada_granta_sedan.png',
                'slogan' => 'Классика семейства LADA Granta',
                'active' => 1,
            ],
            [
                'car_model_id' => '1',
                'car_type_id' => '2',
                'preview' => false,
                'price' => 572900,
                'special_price' => 572900,
                'credit_from' => 5289,
                'count'=>0,
                'image' => '/images/slider/mini/granta/mobile/lada_granta_liftback.png',
                'slogan' => 'Спортивный облик LADA Granta',
                'active' => 1,
            ],
            [
                'car_model_id' => '1',
                'car_type_id' => '3',
                'preview' => false,
                'price' => 579900,
                'special_price' => 579900,
                'credit_from' => 5356,
                'count'=>0,
                'image' => '/images/slider/mini/granta/mobile/lada_granta_universal.png',
                'slogan' => 'Увеличенный вместительный багажник',
                'active' => 1,
            ],
            [
                'car_model_id' => '1',
                'car_type_id' => '4',
                'preview' => false,
                'price' => 674900,
                'special_price' => 674900,
                'credit_from' => 6265,
                'count'=>0,
                'image' => '/images/slider/mini/granta/mobile/lada_granta_cross.png',
                'slogan' => 'Увеличенный дорожный просвет, практичный багажник',
                'active' => 0,
            ],
            [
                'car_model_id' => '1',
                'car_type_id' => '5',
                'preview' => false,
                'price' => 741900,
                'special_price' => 741900,
                'credit_from' => 6906,
                'count'=>0,
                'image' => '/images/slider/mini/granta/mobile/lada_granta_drive_active.png',
                'slogan' => 'Автомобиль, всегда готовый к драйву',
                'active' => 1,
            ],
            [
                'car_model_id' => '1',
                'car_type_id' => '6',
                'preview' => false,
                'price' => 604500,
                'special_price' => 604500,
                'credit_from' => 5591,
                'count'=>0,
                'image' => '/images/slider/mini/granta/mobile/lada_granta_hatcback.png',
                'slogan' => 'Удобный компактный багажник',
                'active' => 1,
            ],
            [
                'car_model_id' => '2',
                'car_type_id' => '1',
                'preview' => true,
                'price' => 783900,
                'special_price' => 783900,
                'credit_from' => 7308,
                'count'=>0,
                'image' => '/images/slider/mini/vesta/mobile/lada_vesta_sedan.png',
                'slogan' => 'Классика семейства LADA Vesta',
                'active' => 1,
            ],
            [
                'car_model_id' => '2',
                'car_type_id' => '4',
                'preview' => false,
                'price' => 921900,
                'special_price' => 921900,
                'credit_from' => 8723,
                'count'=>0,
                'image' => '/images/slider/mini/vesta/mobile/lada_vesta_cross.png',
                'slogan' => 'Стиль стремительного седана и проходимость уверенного в себе кроссовера',
                'active' => 1,
            ],
            [
                'car_model_id' => '2',
                'car_type_id' => '7',
                'preview' => false,
                'price' => 880900,
                'special_price' => 870900,
                'credit_from' => 8236,
                'count'=>0,
                'image' => '/images/slider/mini/vesta/mobile/lada_vesta_sw.png',
                'slogan' => 'Увеличенное пространство для пассажиров заднего ряда',
                'active' => 1,
            ],
            [
                'car_model_id' => '2',
                'car_type_id' => '8',
                'preview' => false,
                'price' => 995900,
                'special_price' => 985900,
                'credit_from' => 9336,
                'count'=>0,
                'image' => '/images/slider/mini/vesta/mobile/lada_vesta_sw_cross.png',
                'slogan' => 'Увеличенный дорожный просвет и драйверские настройки шасси, защитный обвес',
                'active' => 1,
            ],
            [
                'car_model_id' => '2',
                'car_type_id' => '9',
                'preview' => false,
                'price' => 983900,
                'special_price' => 973900,
                'credit_from' => 9221,
                'count'=>0,
                'image' => '/images/slider/mini/vesta/mobile/lada_vesta_cng.png',
                'slogan' => 'Возможность использовать два вида топлива: сжатый природный газ (метан) и бензин',
                'active' => 0,
            ],
            [
                'car_model_id' => '2',
                'car_type_id' => '10',
                'preview' => false,
                'price' => 1209900,
                'special_price' => 1199900,
                'credit_from' => 11383,
                'count'=>0,
                'image' => '/images/slider/mini/vesta/mobile/lada_vesta_sport.png',
                'slogan' => 'Спортивный дизайн, форсированный мотор до 145 л., повышенный уровень безопасности',
                'active' => 1,
            ],
            [
                'car_model_id' => '3',
                'car_type_id' => '20',
                'preview' => false,
                'price' => 761900,
                'special_price' => 751900,
                'credit_from' => 7097,
                'count'=>0,
                'image' => '/images/slider/mini/xray/mobile/lada_xray_xray.png',
                'slogan' => 'Высокий внедорожный клиренс',
                'active' => 1,
            ],
            [
                'car_model_id' => '3',
                'car_type_id' => '4',
                'preview' => true,
                'price' => 858900,
                'special_price' => 848900,
                'credit_from' => 8025,
                'count'=>0,
                'image' => '/images/slider/mini/xray/mobile/lada_xray_cross.png',
                'slogan' => 'Увеличенный дорожный просвет, защитный обвес',
                'active' => 1,
            ],
            [
                'car_model_id' => '4',
                'car_type_id' => '11',
                'preview' => true,
                'price' => 649900,
                'special_price' => 649900,
                'credit_from' => 6026,
                'count'=>0,
                'image' => '/images/slider/mini/4x4/mobile/lada_4x4_three.png',
                'slogan' => 'Полный привод, кузов из оцинкованной стали, внедорожник',
                'active' => 1,
            ],
            [
                'car_model_id' => '4',
                'car_type_id' => '12',
                'preview' => false,
                'price' => 663900,
                'special_price' => 663900,
                'credit_from' => NULL,
                'count'=>0,
                'image' => '/images/slider/mini/4x4/mobile/lada_4x4_three_urban.png',
                'slogan' => 'Компактные габариты и полный привод',
                'active' => 0,
            ],
            [
                'car_model_id' => '4',
                'car_type_id' => '13',
                'preview' => false,
                'price' => 727900,
                'special_price' => 727900,
                'credit_from' => 6772,
                'count'=>0,
                'image' => '/images/slider/mini/4x4/mobile/lada_4x4_five.png',
                'slogan' => 'Полный привод, кузов из оцинкованной стали, 5-ти дверный внедорожник',
                'active' => 1,
            ],
            [
                'car_model_id' => '4',
                'car_type_id' => '14',
                'preview' => false,
                'price' => 706900,
                'special_price' => 706900,
                'credit_from' => NULL,
                'count'=>0,
                'image' => '/images/slider/mini/4x4/mobile/lada_4x4_five_urban.png',
                'slogan' => 'Кондиционер, электростеклоподъемники, электропривод и электрообогрев наружных зеркал',
                'active' => 0,
            ],
            [
                'car_model_id' => '4',
                'car_type_id' => '15',
                'preview' => false,
                'price' => 742900,
                'special_price' => 742900,
                'credit_from' => NULL,
                'count'=>0,
                'image' => '/images/slider/mini/4x4/mobile/lada_4x4_bronto.png',
                'slogan' => 'Увеличенный дорожный просвет, усиленный задний мост, литые колеса с шинами c активным грунтовым протектором',
                'active' => 0,
            ],
            [
                'car_model_id' => '5',
                'car_type_id' => '3',
                'preview' => true,
                'price' => 768900,
                'special_price' => 768900,
                'credit_from' => 7164,
                'count'=>0,
                'image' => '/images/slider/mini/largus/mobile/lada_largus_universal.png',
                'slogan' => 'Увеличенный дорожный просвет, защитный обвес',
                'active' => 1,
            ],
            [
                'car_model_id' => '5',
                'car_type_id' => '4',
                'preview' => false,
                'price' => 938900,
                'special_price' => 938900,
                'credit_from' => 8790,
                'count'=>0,
                'image' => '/images/slider/mini/largus/mobile/lada_largus_cross.png',
                'slogan' => 'Сжатый природный газ (метан), сниженные затраты на топливо',
                'active' => 1,
            ],
            [
                'car_model_id' => '5',
                'car_type_id' => '25',
                'preview' => false,
                'price' => 704900,
                'special_price' => 704900,
                'credit_from' => NULL,
                'count'=>333,
                'image' => '/images/slider/mini/largus/mobile/lada_largus_cross.png',
                'slogan' => 'Новый LADA Largus.</br> Комфорт на максимум.',
                'active' => 0,
            ],
            [
                'car_model_id' => '5',
                'car_type_id' => '16',
                'preview' => false,
                'price' => 805900,
                'special_price' => 725310,
                'credit_from' => NULL,
                'count'=>0,
                'image' => '/images/slider/mini/largus/mobile/lada_largus_universal_cng.png',
                'slogan' => 'Увеличенный дорожный просвет, защитный обвес, улучшенный дизайн',
                'active' => 0,
            ],
            [
                'car_model_id' => '5',
                'car_type_id' => '17',
                'preview' => false,
                'price' => 992900,
                'special_price' => 834900,
                'credit_from' => NULL,
                'count'=>0,
                'image' => '/images/slider/mini/largus/mobile/lada_largus_cross_cng.png',
                'slogan' => 'Увеличенный дорожный просвет, сжатый природный газ (метан) и бензин',
                'active' => 0,
            ],
            [
                'car_model_id' => '5',
                'car_type_id' => '18',
                'preview' => false,
                'price' => 0,
                'special_price' => 0,
                'credit_from' => NULL,
                'count'=>0,
                'image' => '/images/slider/mini/largus/mobile/lada_largus_minivan.png',
                'slogan' => 'Вместительный грузовой отсек, высокий клиренс, широкий дверной проем',
                'active' => 0,
            ],
            [
                'car_model_id' => '5',
                'car_type_id' => '19',
                'preview' => false,
                'price' => 938900,
                'special_price' => 780900,
                'credit_from' => NULL,
                'count'=>0,
                'image' => '/images/slider/mini/largus/mobile/lada_largus_minivan_cng.png',
                'slogan' => 'Высокая грузоподъемность, двойные задние распашные двери, низкий порог, высокая крыша',
                'active' => 0,
            ],
            [
                'car_model_id' => '6',
                'car_type_id' => '22',
                'preview' => false,
                'price' => 770000,
                'special_price' => 730000,
                'credit_from' => NULL,
                'count'=>0,
                'image' => '/images/slider/mini/4x4/mobile/lada_niva.png',
                'slogan' => 'На край света и обратно',
                'active' => 1,
            ],
            [
                'car_model_id' => '6',
                'car_type_id' => '23',
                'preview' => false,
                'price' => 860000,
                'special_price' => 820000,
                'credit_from' => NULL,
                'count'=>0,
                'image' => '/images/slider/mini/4x4/mobile/lada_niva_extravaganza.png',
                'slogan' => 'На край света и обратно',
                'active' => 1,
            ],
            [
                'car_model_id' => '6',
                'car_type_id' => '24',
                'preview' => true,
                'price' => 820900,
                'special_price' => 820900,
                'credit_from' => 7662,
                'count'=>0,
                'image' => '/images/slider/mini/niva/mobile/lada_niva_travel.png',
                'slogan' => 'Выросла дикой, приучена к городу.',
                'active' => 1,
            ],
        ];

        DB::table('car_model_car_type')->insert($model_types);
    }
}
