<?php

use Illuminate\Database\Seeder;

class CarModelCarTypeTableSeeder extends Seeder
{
    public function run()
    {
        $model_types = [
            [
                'car_model_id' => '1',
                'car_type_id' => '1',
                'preview' => true,
                'price' => 727900,
                'special_price' => 727900,
                'credit_from' => 0,
                'count'=>0,
                'image' => '/images/slider/mini/granta/mobile/lada_granta_sedan.png',
                'slogan' => 'Классика семейства LADA Granta',
                'active' => 1,
            ],
            [
                'car_model_id' => '1',
                'car_type_id' => '2',
                'preview' => false,
                'price' => 749900,
                'special_price' => 749900,
                'credit_from' => 0,
                'count'=>0,
                'image' => '/images/slider/mini/granta/mobile/lada_granta_liftback.png',
                'slogan' => 'Спортивный облик LADA Granta',
                'active' => 1,
            ],
            [
                'car_model_id' => '1',
                'car_type_id' => '6',
                'preview' => false,
                'price' => 778500,
                'special_price' => 778500,
                'credit_from' => 0,
                'count'=>0,
                'image' => '/images/slider/mini/granta/mobile/lada_granta_hatcback.png',
                'slogan' => 'Удобный компактный багажник',
                'active' => 1,
            ],
            [
                'car_model_id' => '1',
                'car_type_id' => '3',
                'preview' => false,
                'price' => 753900,
                'special_price' => 753900,
                'credit_from' => 0,
                'count'=>0,
                'image' => '/images/slider/mini/granta/mobile/lada_granta_universal.png',
                'slogan' => 'Увеличенный вместительный багажник',
                'active' => 1,
            ],
            [
                'car_model_id' => '1',
                'car_type_id' => '4',
                'preview' => false,
                'price' => 854900,
                'special_price' => 854900,
                'credit_from' => 0,
                'count'=>0,
                'image' => '/images/slider/mini/granta/mobile/lada_granta_cross.png',
                'slogan' => 'Увеличенный дорожный просвет, практичный багажник',
                'active' => 0,
            ],
            [
                'car_model_id' => '1',
                'car_type_id' => '5',
                'preview' => false,
                'price' => 940900,
                'special_price' => 940900,
                'credit_from' => 0,
                'count'=>0,
                'image' => '/images/slider/mini/granta/mobile/lada_granta_drive_active.png',
                'slogan' => 'Автомобиль, всегда готовый к драйву',
                'active' => 1,
            ],
            [
                'car_model_id' => '2',
                'car_type_id' => '1',
                'preview' => true,
                'price' => 1121900,
                'special_price' => 1121900,
                'credit_from' => 0,
                'count'=>0,
                'image' => '/images/slider/mini/vesta/mobile/lada_vesta_sedan.png',
                'slogan' => 'Классика семейства LADA Vesta',
                'active' => 1,
            ],
            [
                'car_model_id' => '2',
                'car_type_id' => '4',
                'preview' => false,
                'price' => 1269900,
                'special_price' => 1269900,
                'credit_from' => 0,
                'count'=>0,
                'image' => '/images/slider/mini/vesta/mobile/lada_vesta_cross.png',
                'slogan' => 'Стиль стремительного седана и проходимость уверенного в себе кроссовера',
                'active' => 1,
            ],
            [
                'car_model_id' => '2',
                'car_type_id' => '7',
                'preview' => false,
                'price' => 1213900,
                'special_price' => 1213900,
                'credit_from' => 0,
                'count'=>0,
                'image' => '/images/slider/mini/vesta/mobile/lada_vesta_sw.png',
                'slogan' => 'Увеличенное пространство для пассажиров заднего ряда',
                'active' => 1,
            ],
            [
                'car_model_id' => '2',
                'car_type_id' => '8',
                'preview' => false,
                'price' => 1328900,
                'special_price' => 1328900,
                'credit_from' => 0,
                'count'=>0,
                'image' => '/images/slider/mini/vesta/mobile/lada_vesta_sw_cross.png',
                'slogan' => 'Увеличенный дорожный просвет и драйверские настройки шасси, защитный обвес',
                'active' => 1,
            ],
            [
                'car_model_id' => '2',
                'car_type_id' => '9',
                'preview' => false,
                'price' => 1316900,
                'special_price' => 1316900,
                'credit_from' => 0,
                'count'=>0,
                'image' => '/images/slider/mini/vesta/mobile/lada_vesta_cng.png',
                'slogan' => 'Возможность использовать два вида топлива: сжатый природный газ (метан) и бензин',
                'active' => 0,
            ],
            [
                'car_model_id' => '2',
                'car_type_id' => '10',
                'preview' => false,
                'price' => 1597900,
                'special_price' => 1597900,
                'credit_from' => 0,
                'count'=>0,
                'image' => '/images/slider/mini/vesta/mobile/lada_vesta_sport.png',
                'slogan' => 'Спортивный дизайн, форсированный мотор до 145 л., повышенный уровень безопасности',
                'active' => 1,
            ],
            [
                'car_model_id' => '3',
                'car_type_id' => '20',
                'preview' => false,
                'price' => 1106900,
                'special_price' => 1106900,
                'credit_from' => 0,
                'count'=>0,
                'image' => '/images/slider/mini/xray/mobile/lada_xray_xray.png',
                'slogan' => 'Высокий внедорожный клиренс',
                'active' => 1,
            ],
            [
                'car_model_id' => '3',
                'car_type_id' => '4',
                'preview' => true,
                'price' => 1249900,
                'special_price' => 1249900,
                'credit_from' => 0,
                'count'=>0,
                'image' => '/images/slider/mini/xray/mobile/lada_xray_cross.png',
                'slogan' => 'Увеличенный дорожный просвет, защитный обвес',
                'active' => 1,
            ],
            [
                'car_model_id' => '5',
                'car_type_id' => '3',
                'preview' => true,
                'price' => 1235900,
                'special_price' => 1235900,
                'credit_from' => 0,
                'count'=>0,
                'image' => '/images/slider/mini/largus/mobile/lada_largus_universal.png',
                'slogan' => 'Увеличенный дорожный просвет, защитный обвес',
                'active' => 1,
            ],
            [
                'car_model_id' => '5',
                'car_type_id' => '4',
                'preview' => false,
                'price' => 1377900,
                'special_price' => 1377900,
                'credit_from' => 0,
                'count'=>0,
                'image' => '/images/slider/mini/largus/mobile/lada_largus_cross.png',
                'slogan' => 'Сжатый природный газ (метан), сниженные затраты на топливо',
                'active' => 1,
            ],
            [
                'car_model_id' => '6',
                'car_type_id' => '24',
                'preview' => true,
                'price' => 1066900,
                'special_price' => 1066900,
                'credit_from' => 0,
                'count'=>0,
                'image' => '/images/slider/mini/niva/mobile/lada_niva_travel.png',
                'slogan' => 'Выросла дикой, приучена к городу.',
                'active' => 1,
            ],
            [
                'car_model_id' => '7',
                'car_type_id' => '11',
                'preview' => true,
                'price' => 818900,
                'special_price' => 818900,
                'credit_from' => 0,
                'count'=>0,
                'image' => '/images/slider/mini/4x4/lada_4x4_three.png',
                'slogan' => 'Новое имя для легенды',
                'active' => 1,
            ],
            [
                'car_model_id' => '7',
                'car_type_id' => '13',
                'preview' => false,
                'price' => 918900,
                'special_price' => 918900,
                'credit_from' => 0,
                'count'=>0,
                'image' => '/images/slider/mini/4x4/lada_4x4_five.png',
                'slogan' => 'Полный привод, кузов из оцинкованной стали, 5-ти дверный внедорожник',
                'active' => 1,
            ],
        ];

        DB::table('car_model_car_type')->insert($model_types);
    }
}
