<?php

use Illuminate\Database\Seeder;

class ComplectationTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $granta = [
            // drive_active
            [
                'model_id' => 1,
                'type_id' => 5,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort Light',
                'price' => 719900,
                'sort' => 1,
            ],
            [
                'model_id' => 1,
                'type_id' => 5,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort',
                'price' => 726900,
                'sort' => 2,
            ],
            // hatchback
            [
                'model_id' => 1,
                'type_id' => 6,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5МТ',
                'title' => 'Classic',
                'price' => 577500,
                'sort' => 1,
            ],
            [
                'model_id' => 1,
                'type_id' => 6,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort Light',
                'price' => 618500,
                'sort' => 2,
            ],
            [
                'model_id' => 1,
                'type_id' => 6,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort',
                'price' => 625500,
                'sort' => 3,
            ],
            [
                'model_id' => 1,
                'type_id' => 6,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '98 л.с.',
                'transmission' => '4AТ',
                'title' => 'Comfort',
                'price' => 715500,
                'sort' => 4,
            ],
            [
                'model_id' => 1,
                'type_id' => 6,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '98 л.с.',
                'transmission' => '4AТ',
                'title' => 'Luxe',
                'price' => 759800,
                'sort' => 5,
            ],
            // liftback
            [
                'model_id' => 1,
                'type_id' => 2,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Standard',
                'price' => 553900,
                'sort' => 1,
            ],
            [
                'model_id' => 1,
                'type_id' => 2,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Classic',
                'price' => 582500,
                'sort' => 2,
            ],
            [
                'model_id' => 1,
                'type_id' => 2,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Comfort Light',
                'price' => 623500,
                'sort' => 3,
            ],
            [
                'model_id' => 1,
                'type_id' => 2,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Comfort',
                'price' => 630500,
                'sort' => 4,
            ],
            [
                'model_id' => 1,
                'type_id' => 2,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => '#CLUB',
                'price' => 652900,
                'sort' => 5,
            ],
            [
                'model_id' => 1,
                'type_id' => 2,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Luxe',
                'price' => 674800,
                'sort' => 6,
            ],
            [
                'model_id' => 1,
                'type_id' => 2,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5MT',
                'title' => 'Comfort Light',
                'price' => 648500,
                'sort' => 7,
            ],
            [
                'model_id' => 1,
                'type_id' => 2,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5MT',
                'title' => 'Comfort',
                'price' => 655500,
                'sort' => 8,
            ],
            [
                'model_id' => 1,
                'type_id' => 2,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5MT',
                'title' => '#CLUB',
                'price' => 677900,
                'sort' => 9,
            ],
            [
                'model_id' => 1,
                'type_id' => 2,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5MT',
                'title' => 'Luxe',
                'price' => 699800,
                'sort' => 10,
            ],
            [
                'model_id' => 1,
                'type_id' => 2,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '98 л.с.',
                'transmission' => '4AT',
                'title' => 'Comfort',
                'price' => 720500,
                'sort' => 11,
            ],
            [
                'model_id' => 1,
                'type_id' => 2,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '98 л.с.',
                'transmission' => '4AT',
                'title' => 'Luxe',
                'price' => 764800,
                'sort' => 12,
            ],
            // sedan
            [
                'model_id' => 1,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Standard',
                'price' => 531900,
                'sort' => 1,
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Classic',
                'price' => 562500,
                'sort' => 2,
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Comfort Light',
                'price' => 603500,
                'sort' => 3,
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Comfort',
                'price' => 610500,
                'sort' => 4,
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => '#CLUB',
                'price' => 632900,
                'sort' => 5,
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Luxe',
                'price' => 654800,
                'sort' => 6,
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5MT',
                'title' => 'Comfort Light',
                'price' => 628500,
                'sort' => 7,
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5MT',
                'title' => 'Comfort',
                'price' => 635500,
                'sort' => 8,
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5MT',
                'title' => '#CLUB',
                'price' => 657900,
                'sort' => 9,
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5MT',
                'title' => 'Luxe',
                'price' => 679800,
                'sort' => 10,
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '98 л.с.',
                'transmission' => '4AT',
                'title' => 'Comfort Light',
                'price' => 693500,
                'sort' => 11,
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '98 л.с.',
                'transmission' => '4AT',
                'title' => 'Comfort',
                'price' => 700500,
                'sort' => 12,
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '98 л.с.',
                'transmission' => '4AT',
                'title' => 'Luxe',
                'price' => 744800,
                'sort' => 13,
            ],
            // universal
            [
                'model_id' => 1,
                'type_id' => 3,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Standard',
                'price' => 560900,
                'sort' => 1,
            ],
            [
                'model_id' => 1,
                'type_id' => 3,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Classic',
                'price' => 589500,
                'sort' => 2,
            ],
            [
                'model_id' => 1,
                'type_id' => 3,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Comfort Light',
                'price' => 630500,
                'sort' => 3,
            ],
            [
                'model_id' => 1,
                'type_id' => 3,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Comfort',
                'price' => 637500,
                'sort' => 4,
            ],
            [
                'model_id' => 1,
                'type_id' => 3,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5MT',
                'title' => 'Comfort',
                'price' => 662500,
                'sort' => 5,
            ],
            [
                'model_id' => 1,
                'type_id' => 3,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5MT',
                'title' => 'Luxe',
                'price' => 706800,
                'sort' => 6,
            ],
            [
                'model_id' => 1,
                'type_id' => 3,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '98 л.с.',
                'transmission' => '4AT',
                'title' => 'Comfort',
                'price' => 727500,
                'sort' => 7,
            ],
            [
                'model_id' => 1,
                'type_id' => 3,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '98 л.с.',
                'transmission' => '4AT',
                'title' => 'Luxe',
                'price' => 771800,
                'sort' => 8,
            ],
        ];

        $vesta = [];

        $complectations = array_merge($granta, $vesta);
        DB::table('complectations')->insert($complectations);
    }
}
