<?php

use Illuminate\Database\Seeder;

class ComplectationTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $granta = [
            // drive_active
            [
                'model_id' => 1,
                'type_id' => 5,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort Light',
                'price' => 775900,
                'sort' => 1,
            ],
            [
                'model_id' => 1,
                'type_id' => 5,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort',
                'price' => 782900,
                'sort' => 2,
            ],
            // hatchback
            [
                'model_id' => 1,
                'type_id' => 6,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5МТ',
                'title' => 'Classic',
                'price' => 638500,
                'sort' => 1,
            ],
            [
                'model_id' => 1,
                'type_id' => 6,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort Light',
                'price' => 679500,
                'sort' => 2,
            ],
            [
                'model_id' => 1,
                'type_id' => 6,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort',
                'price' => 686500,
                'sort' => 3,
            ],
            [
                'model_id' => 1,
                'type_id' => 6,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '98 л.с.',
                'transmission' => '4AТ',
                'title' => 'Comfort',
                'price' => 776500,
                'sort' => 4,
            ],
            [
                'model_id' => 1,
                'type_id' => 6,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '98 л.с.',
                'transmission' => '4AТ',
                'title' => 'Luxe',
                'price' => 825800,
                'sort' => 5,
            ],
            // liftback
            [
                'model_id' => 1,
                'type_id' => 2,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Standard',
                'price' => 609900,
                'sort' => 1,
            ],
            [
                'model_id' => 1,
                'type_id' => 2,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Classic',
                'price' => 641500,
                'sort' => 2,
            ],
            [
                'model_id' => 1,
                'type_id' => 2,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Comfort Light',
                'price' => 682500,
                'sort' => 3,
            ],
            [
                'model_id' => 1,
                'type_id' => 2,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Comfort',
                'price' => 689500,
                'sort' => 4,
            ],
            [
                'model_id' => 1,
                'type_id' => 2,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => '#CLUB',
                'price' => 711900,
                'sort' => 5,
            ],
            [
                'model_id' => 1,
                'type_id' => 2,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Luxe',
                'price' => 738800,
                'sort' => 6,
            ],
            [
                'model_id' => 1,
                'type_id' => 2,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5MT',
                'title' => 'Comfort Light',
                'price' => 707500,
                'sort' => 7,
            ],
            [
                'model_id' => 1,
                'type_id' => 2,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5MT',
                'title' => 'Comfort',
                'price' => 714500,
                'sort' => 8,
            ],
            [
                'model_id' => 1,
                'type_id' => 2,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5MT',
                'title' => '#CLUB',
                'price' => 736900,
                'sort' => 9,
            ],
            [
                'model_id' => 1,
                'type_id' => 2,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5MT',
                'title' => 'Luxe',
                'price' => 763800,
                'sort' => 10,
            ],
            [
                'model_id' => 1,
                'type_id' => 2,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '98 л.с.',
                'transmission' => '4AT',
                'title' => 'Comfort',
                'price' => 779500,
                'sort' => 11,
            ],
            [
                'model_id' => 1,
                'type_id' => 2,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '98 л.с.',
                'transmission' => '4AT',
                'title' => 'Luxe',
                'price' => 828800,
                'sort' => 12,
            ],
            // sedan
            [
                'model_id' => 1,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Standard',
                'price' => 587900,
                'sort' => 1,
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Classic',
                'price' => 621500,
                'sort' => 2,
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Comfort Light',
                'price' => 662500,
                'sort' => 3,
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Comfort',
                'price' => 669500,
                'sort' => 4,
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => '#CLUB',
                'price' => 691900,
                'sort' => 5,
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Luxe',
                'price' => 718800,
                'sort' => 6,
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5MT',
                'title' => 'Comfort Light',
                'price' => 687500,
                'sort' => 7,
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5MT',
                'title' => 'Comfort',
                'price' => 694500,
                'sort' => 8,
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5MT',
                'title' => '#CLUB',
                'price' => 716900,
                'sort' => 9,
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5MT',
                'title' => 'Luxe',
                'price' => 743800,
                'sort' => 10,
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '98 л.с.',
                'transmission' => '4AT',
                'title' => 'Comfort Light',
                'price' => 752500,
                'sort' => 11,
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '98 л.с.',
                'transmission' => '4AT',
                'title' => 'Comfort',
                'price' => 759500,
                'sort' => 12,
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '98 л.с.',
                'transmission' => '4AT',
                'title' => 'Luxe',
                'price' => 808800,
                'sort' => 13,
            ],
            // universal
            [
                'model_id' => 1,
                'type_id' => 3,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Standard',
                'price' => 613900,
                'sort' => 1,
            ],
            [
                'model_id' => 1,
                'type_id' => 3,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Classic',
                'price' => 620500,
                'sort' => 2,
            ],
            [
                'model_id' => 1,
                'type_id' => 3,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Comfort Light',
                'price' => 686500,
                'sort' => 3,
            ],
            [
                'model_id' => 1,
                'type_id' => 3,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Comfort',
                'price' => 693500,
                'sort' => 4,
            ],
            [
                'model_id' => 1,
                'type_id' => 3,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5MT',
                'title' => 'Comfort',
                'price' => 718500,
                'sort' => 5,
            ],
            [
                'model_id' => 1,
                'type_id' => 3,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5MT',
                'title' => 'Luxe',
                'price' => 767800,
                'sort' => 6,
            ],
            [
                'model_id' => 1,
                'type_id' => 3,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '98 л.с.',
                'transmission' => '4AT',
                'title' => 'Comfort',
                'price' => 783500,
                'sort' => 7,
            ],
            [
                'model_id' => 1,
                'type_id' => 3,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '98 л.с.',
                'transmission' => '4AT',
                'title' => 'Luxe',
                'price' => 832800,
                'sort' => 8,
            ],
        ];

        $vesta = [
            // Vesta sedan
            [
                'model_id' => 2,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Classic',
                'price' => 835900,
                'sort' => 1,
            ],
            [
                'model_id' => 2,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort Light',
                'price' => 885900,
                'sort' => 2,
            ],
            [
                'model_id' => 2,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort',
                'price' => 896900,
                'sort' => 3,
            ],
            [
                'model_id' => 2,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe EnjoY',
                'price' => 1000900,
                'sort' => 4,
            ],
            [
                'model_id' => 2,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe EnjoY Pro',
                'price' => 1019900,
                'sort' => 5,
            ],
            [
                'model_id' => 2,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Exclusive',
                'price' => 1075900,
                'sort' => 6,
            ],
            [
                'model_id' => 2,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '113 л.с.',
                'transmission' => 'АТ',
                'title' => 'Comfort Light',
                'price' => 985900,
                'sort' => 7,
            ],
            [
                'model_id' => 2,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '113 л.с.',
                'transmission' => 'АТ',
                'title' => 'Comfort',
                'price' => 996900,
                'sort' => 8,
            ],
            [
                'model_id' => 2,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '113 л.с.',
                'transmission' => 'АТ',
                'title' => 'Luxe EnjoY Pro',
                'price' => 1119900,
                'sort' => 9,
            ],
            [
                'model_id' => 2,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '113 л.с.',
                'transmission' => 'АТ',
                'title' => 'Exclusive',
                'price' => 1175900,
                'sort' => 10,
            ],
            // Vesta Cross
            [
                'model_id' => 2,
                'type_id' => 4,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort',
                'price' => 983900,
                'sort' => 1,
            ],
            [
                'model_id' => 2,
                'type_id' => 4,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => '[BLACK]',
                'price' => 1018900,
                'sort' => 2,
            ],
            [
                'model_id' => 2,
                'type_id' => 4,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe EnjoY',
                'price' => 1075900,
                'sort' => 3,
            ],
            [
                'model_id' => 2,
                'type_id' => 4,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe EnjoY Pro',
                'price' => 1094900,
                'sort' => 4,
            ],
            [
                'model_id' => 2,
                'type_id' => 4,
                'engine' => '1,8 л',
                'flap' => '16-кл.',
                'capacity' => '122 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort',
                'price' => 1008900,
                'sort' => 5,
            ],
            [
                'model_id' => 2,
                'type_id' => 4,
                'engine' => '1,8 л',
                'flap' => '16-кл.',
                'capacity' => '122 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe EnjoY Pro',
                'price' => 1119900,
                'sort' => 6,
            ],
            [
                'model_id' => 2,
                'type_id' => 4,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '113 л.с.',
                'transmission' => 'АТ',
                'title' => 'Comfort',
                'price' => 1073900,
                'sort' => 7,
            ],
            [
                'model_id' => 2,
                'type_id' => 4,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '113 л.с.',
                'transmission' => 'АТ',
                'title' => '[BLACK]',
                'price' => 1108900,
                'sort' => 8,
            ],
            [
                'model_id' => 2,
                'type_id' => 4,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '113 л.с.',
                'transmission' => 'АТ',
                'title' => 'Luxe EnjoY Pro',
                'price' => 1184900,
                'sort' => 9,
            ],
            // Vesta SW
            [
                'model_id' => 2,
                'type_id' => 7,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Classic Start',
                'price' => 927900,
                'sort' => 1,
            ],
            [
                'model_id' => 2,
                'type_id' => 7,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort Light',
                'price' => 944900,
                'sort' => 2,
            ],
            [
                'model_id' => 2,
                'type_id' => 7,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort',
                'price' => 955900,
                'sort' => 3,
            ],
            [
                'model_id' => 2,
                'type_id' => 7,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe EnjoY',
                'price' => 1062900,
                'sort' => 4,
            ],
            [
                'model_id' => 2,
                'type_id' => 7,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe EnjoY Pro',
                'price' => 1081900,
                'sort' => 5,
            ],
            [
                'model_id' => 2,
                'type_id' => 7,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Exclusive',
                'price' => 1137900,
                'sort' => 6,
            ],
            [
                'model_id' => 2,
                'type_id' => 7,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '113 л.с.',
                'transmission' => 'АТ',
                'title' => 'Comfort Light',
                'price' => 1044900,
                'sort' => 7,
            ],
            [
                'model_id' => 2,
                'type_id' => 7,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '113 л.с.',
                'transmission' => 'АТ',
                'title' => 'Comfort',
                'price' => 1055900,
                'sort' => 8,
            ],
            [
                'model_id' => 2,
                'type_id' => 7,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '113 л.с.',
                'transmission' => 'АТ',
                'title' => 'Luxe EnjoY Pro',
                'price' => 1181900,
                'sort' => 9,
            ],
            [
                'model_id' => 2,
                'type_id' => 7,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '113 л.с.',
                'transmission' => 'АТ',
                'title' => 'Exclusive',
                'price' => 1237900,
                'sort' => 10,
            ],
            // Vesta SW Cross
            [
                'model_id' => 2,
                'type_id' => 8,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort',
                'price' => 1042900,
                'sort' => 1,
            ],
            [
                'model_id' => 2,
                'type_id' => 8,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => '[BLACK]',
                'price' => 1077900,
                'sort' => 2,
            ],
            [
                'model_id' => 2,
                'type_id' => 8,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe EnjoY ',
                'price' => 1137900,
                'sort' => 3,
            ],
            [
                'model_id' => 2,
                'type_id' => 8,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe EnjoY Pro',
                'price' => 1156900,
                'sort' => 4,
            ],
            [
                'model_id' => 2,
                'type_id' => 8,
                'engine' => '1,8 л',
                'flap' => '16-кл.',
                'capacity' => '122 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort',
                'price' => 1067900,
                'sort' => 5,
            ],
            [
                'model_id' => 2,
                'type_id' => 8,
                'engine' => '1,8 л',
                'flap' => '16-кл.',
                'capacity' => '122 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe EnjoY Pro',
                'price' => 1181900,
                'sort' => 6,
            ],
            [
                'model_id' => 2,
                'type_id' => 8,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '113 л.с.',
                'transmission' => 'АТ',
                'title' => 'Comfort',
                'price' => 1132900,
                'sort' => 7,
            ],
            [
                'model_id' => 2,
                'type_id' => 8,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '113 л.с.',
                'transmission' => 'АТ',
                'title' => '[BLACK]',
                'price' => 1167900,
                'sort' => 8,
            ],
            [
                'model_id' => 2,
                'type_id' => 8,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '113 л.с.',
                'transmission' => 'АТ',
                'title' => 'Luxe EnjoY Pro',
                'price' => 1246900,
                'sort' => 9,
            ],
            // Vesta CNG
            [
                'model_id' => 2,
                'type_id' => 9,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => NULL,
                'transmission' => '5МТ',
                'title' => 'Classic Start',
                'price' => 1030900,
                'sort' => 1,
            ],
            [
                'model_id' => 2,
                'type_id' => 9,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => NULL,
                'transmission' => '5МТ',
                'title' => 'Comfort',
                'price' => 1061900,
                'sort' => 2,
            ],
            [
                'model_id' => 2,
                'type_id' => 9,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => NULL,
                'transmission' => '5МТ',
                'title' => 'Luxe EnjoY',
                'price' => 1156900,
                'sort' => 3,
            ],
            // Vesta Sport
            [
                'model_id' => 2,
                'type_id' => 10,
                'engine' => '1,8 л',
                'flap' => '16-кл.',
                'capacity' => '145 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe',
                'price' => 1256900,
                'sort' => 1,
            ],
            [
                'model_id' => 2,
                'type_id' => 10,
                'engine' => '1,8 л',
                'flap' => '16-кл.',
                'capacity' => '145 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe EnjoY Pro',
                'price' => 1312900,
                'sort' => 2,
            ],
            // Xray
            [
                'model_id' => 3,
                'type_id' => 20,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Standard',
                'price' => 802900,
                'sort' => 1,
            ],
            [
                'model_id' => 3,
                'type_id' => 20,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Classic Air conditioner',
                'price' => 837900,
                'sort' => 2,
            ],
            [
                'model_id' => 3,
                'type_id' => 20,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort Light',
                'price' => 862900,
                'sort' => 3,
            ],
            [
                'model_id' => 3,
                'type_id' => 20,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort',
                'price' => 870900,
                'sort' => 4,
            ],
            [
                'model_id' => 3,
                'type_id' => 20,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => '#CLUB',
                'price' => 895900,
                'sort' => 5,
            ],
            [
                'model_id' => 3,
                'type_id' => 20,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => '#CLUB EnjoY',
                'price' => 924900,
                'sort' => 6,
            ],
            [
                'model_id' => 3,
                'type_id' => 20,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe',
                'price' => 951900,
                'sort' => 7,
            ],
            [
                'model_id' => 3,
                'type_id' => 20,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5AМТ',
                'title' => 'Comfort Light',
                'price' => 892900,
                'sort' => 8,
            ],
            [
                'model_id' => 3,
                'type_id' => 20,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5AМТ',
                'title' => 'Comfort',
                'price' => 900900,
                'sort' => 9,
            ],
            [
                'model_id' => 3,
                'type_id' => 20,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5AМТ',
                'title' => '#CLUB',
                'price' => 925900,
                'sort' => 10,
            ],
            [
                'model_id' => 3,
                'type_id' => 20,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5AМТ',
                'title' => '#CLUB EnjoY',
                'price' => 954900,
                'sort' => 11,
            ],
            [
                'model_id' => 3,
                'type_id' => 20,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5AМТ',
                'title' => 'Luxe Prestige',
                'price' => 1008900,
                'sort' => 12,
            ],
            // Xray Cross
            [
                'model_id' => 3,
                'type_id' => 4,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Classic',
                'price' => 898900,
                'sort' => 1,
            ],
            [
                'model_id' => 3,
                'type_id' => 4,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort Light',
                'price' => 978900,
                'sort' => 2,
            ],
            [
                'model_id' => 3,
                'type_id' => 4,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort',
                'price' => 986900,
                'sort' => 3,
            ],
            [
                'model_id' => 3,
                'type_id' => 4,
                'engine' => '1,8 л',
                'flap' => '16-кл.',
                'capacity' => '122 л.с.',
                'transmission' => '5МТ',
                'title' => '[BLACK]',
                'price' => 1079900,
                'sort' => 4,
            ],
            [
                'model_id' => 3,
                'type_id' => 4,
                'engine' => '1,8 л',
                'flap' => '16-кл.',
                'capacity' => '122 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe',
                'price' => 1110900,
                'sort' => 5,
            ],
            [
                'model_id' => 3,
                'type_id' => 4,
                'engine' => '1,8 л',
                'flap' => '16-кл.',
                'capacity' => '122 л.с.',
                'transmission' => '5МТ',
                'title' => 'Instinct',
                'price' => 1160900,
                'sort' => 6,
            ],
            [
                'model_id' => 3,
                'type_id' => 4,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '113 л.с.',
                'transmission' => 'AT',
                'title' => 'Classic Optima',
                'price' => 1045900,
                'sort' => 7,
            ],
            [
                'model_id' => 3,
                'type_id' => 4,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '113 л.с.',
                'transmission' => 'AT',
                'title' => 'Comfort Light',
                'price' => 1088900,
                'sort' => 8,
            ],
            [
                'model_id' => 3,
                'type_id' => 4,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '113 л.с.',
                'transmission' => 'AT',
                'title' => 'Comfort',
                'price' => 1096900,
                'sort' => 9,
            ],
            [
                'model_id' => 3,
                'type_id' => 4,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '113 л.с.',
                'transmission' => 'AT',
                'title' => '[BLACK]',
                'price' => 1144900,
                'sort' => 10,
            ],
            [
                'model_id' => 3,
                'type_id' => 4,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '113 л.с.',
                'transmission' => 'AT',
                'title' => 'Luxe',
                'price' => 1175900,
                'sort' => 11,
            ],
            [
                'model_id' => 3,
                'type_id' => 4,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '113 л.с.',
                'transmission' => 'AT',
                'title' => 'Instinct',
                'price' => 1225900,
                'sort' => 12,
            ],
            // Largus Universal
            [
                'model_id' => 5,
                'type_id' => 3,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5МТ',
                'title' => 'Classic',
                'price' => 812900,
                'sort' => 1,
            ],
            [
                'model_id' => 5,
                'type_id' => 3,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort Light',
                'price' => 907900,
                'sort' => 2,
            ],
            [
                'model_id' => 5,
                'type_id' => 3,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort',
                'price' => 916900,
                'sort' => 3,
            ],
            [
                'model_id' => 5,
                'type_id' => 3,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort Light',
                'price' => 927900,
                'sort' => 4,
            ],
            [
                'model_id' => 5,
                'type_id' => 3,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort',
                'price' => 936900,
                'sort' => 5,
            ],
            [
                'model_id' => 5,
                'type_id' => 3,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe Light',
                'price' => 990900,
                'sort' => 7,
            ],
            [
                'model_id' => 5,
                'type_id' => 3,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe',
                'price' => 1010900,
                'sort' => 8,
            ],
            // Largus Cross
            [
                'model_id' => 5,
                'type_id' => 4,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort Light',
                'price' => 982900,
                'sort' => 1,
            ],
            [
                'model_id' => 5,
                'type_id' => 4,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort',
                'price' => 991900,
                'sort' => 2,
            ],
            [
                'model_id' => 5,
                'type_id' => 4,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe Light',
                'price' => 1030900,
                'sort' => 3,
            ],
            [
                'model_id' => 5,
                'type_id' => 4,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe',
                'price' => 1050900,
                'sort' => 4,
            ],
        ];

        // Niva legend
        $niva_legend = [
            // Three doors
            [
                'model_id' => 7,
                'type_id' => 11,
                'engine' => '1,7 л',
                'flap' => '8-кл.',
                'capacity' => '83 л.с.',
                'transmission' => '5МТ',
                'title' => 'Classic',
                'price' => 675900,
                'sort' => 1,
            ],
            [
                'model_id' => 7,
                'type_id' => 11,
                'engine' => '1,7 л',
                'flap' => '8-кл.',
                'capacity' => '83 л.с.',
                'transmission' => '5МТ',
                'title' => '[BLACK]',
                'price' => 760900,
                'sort' => 2,
            ],
            [
                'model_id' => 7,
                'type_id' => 11,
                'engine' => '1,7 л',
                'flap' => '8-кл.',
                'capacity' => '83 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe',
                'price' => 692900,
                'sort' => 3,
            ],
            [
                'model_id' => 7,
                'type_id' => 11,
                'engine' => '1,7 л',
                'flap' => '8-кл.',
                'capacity' => '83 л.с.',
                'transmission' => '5МТ',
                'title' => 'Urban',
                'price' => 751900,
                'sort' => 4,
            ],
            // Five doors
            [
                'model_id' => 7,
                'type_id' => 13,
                'engine' => '1,7 л',
                'flap' => '8-кл.',
                'capacity' => '83 л.с.',
                'transmission' => '5МТ',
                'title' => 'Classic',
                'price' => 755900,
                'sort' => 1,
            ],
            [
                'model_id' => 7,
                'type_id' => 13,
                'engine' => '1,7 л',
                'flap' => '8-кл.',
                'capacity' => '83 л.с.',
                'transmission' => '5МТ',
                'title' => '[BLACK]',
                'price' => 840900,
                'sort' => 2,
            ],
            [
                'model_id' => 7,
                'type_id' => 13,
                'engine' => '1,7 л',
                'flap' => '8-кл.',
                'capacity' => '83 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe',
                'price' => 772900,
                'sort' => 3,
            ],
            [
                'model_id' => 7,
                'type_id' => 13,
                'engine' => '1,7 л',
                'flap' => '8-кл.',
                'capacity' => '83 л.с.',
                'transmission' => '5МТ',
                'title' => 'Urban',
                'price' => 831900,
                'sort' => 4,
            ],
        ];

        $niva_travel = [
            [
                'model_id' => 6,
                'type_id' => 24,
                'engine' => '1,7 л',
                'flap' => '8-кл.',
                'capacity' => '80 л.с.',
                'transmission' => '5МТ',
                'title' => 'Classic',
                'price' => 858900,
                'sort' => 1,
            ],
            [
                'model_id' => 6,
                'type_id' => 24,
                'engine' => '1,7 л',
                'flap' => '8-кл.',
                'capacity' => '80 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort',
                'price' => 915900,
                'sort' => 2,
            ],
            [
                'model_id' => 6,
                'type_id' => 24,
                'engine' => '1,7 л',
                'flap' => '8-кл.',
                'capacity' => '80 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort Off-road',
                'price' => 959900,
                'sort' => 3,
            ],
            [
                'model_id' => 6,
                'type_id' => 24,
                'engine' => '1,7 л',
                'flap' => '8-кл.',
                'capacity' => '80 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe',
                'price' => 1001900,
                'sort' => 4,
            ],
            [
                'model_id' => 6,
                'type_id' => 24,
                'engine' => '1,7 л',
                'flap' => '8-кл.',
                'capacity' => '80 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe Off-road',
                'price' => 1020900,
                'sort' => 5,
            ],
        ];

        $complectations = array_merge($granta, $vesta,  $niva_legend, $niva_travel);
        DB::table('complectations')->insert($complectations);
    }
}
