<?php

use Illuminate\Database\Seeder;

class ComplectationTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $granta = [
            // sedan
            [
                'model_id' => 1,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Classic\'22',
                'price' => 678300,
                'sort' => 1,
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Classic',
                'price' => 761500,
                'sort' => 2,
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Comfort Light',
                'price' => 808500,
                'sort' => 3,
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Comfort',
                'price' => 815500,
                'sort' => 4,
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => '#CLUB',
                'price' => 837900,
                'sort' => 5,
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Luxe',
                'price' => 864800,
                'sort' => 6,
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5MT',
                'title' => 'Comfort Light',
                'price' => 833500,
                'sort' => 7,
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5MT',
                'title' => 'Comfort',
                'price' => 840500,
                'sort' => 8,
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5MT',
                'title' => '#CLUB',
                'price' => 902900,
                'sort' => 9,
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5MT',
                'title' => 'Luxe',
                'price' => 889800,
                'sort' => 10,
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '98 л.с.',
                'transmission' => '4AT',
                'title' => 'Comfort Light',
                'price' => 928500,
                'sort' => 11,
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '98 л.с.',
                'transmission' => '4AT',
                'title' => 'Comfort',
                'price' => 935500,
                'sort' => 12,
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '98 л.с.',
                'transmission' => '4AT',
                'title' => 'Luxe',
                'price' => 984800,
                'sort' => 13,
            ],
            // liftback
            [
                'model_id' => 1,
                'type_id' => 2,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Classic\'22',
                'price' => 698300,
                'sort' => 1,
            ],
            [
                'model_id' => 1,
                'type_id' => 2,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Classic',
                'price' => 781500,
                'sort' => 2,
            ],
            [
                'model_id' => 1,
                'type_id' => 2,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Comfort Light',
                'price' => 828500,
                'sort' => 3,
            ],
            [
                'model_id' => 1,
                'type_id' => 2,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Comfort',
                'price' => 835500,
                'sort' => 4,
            ],
            [
                'model_id' => 1,
                'type_id' => 2,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => '#CLUB',
                'price' => 857900,
                'sort' => 5,
            ],
            [
                'model_id' => 1,
                'type_id' => 2,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Luxe',
                'price' => 884800,
                'sort' => 6,
            ],
            [
                'model_id' => 1,
                'type_id' => 2,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5MT',
                'title' => 'Comfort Light',
                'price' => 853500,
                'sort' => 7,
            ],
            [
                'model_id' => 1,
                'type_id' => 2,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5MT',
                'title' => 'Comfort',
                'price' => 860500,
                'sort' => 8,
            ],
            [
                'model_id' => 1,
                'type_id' => 2,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5MT',
                'title' => '#CLUB',
                'price' => 922900,
                'sort' => 9,
            ],
            [
                'model_id' => 1,
                'type_id' => 2,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5MT',
                'title' => 'Luxe',
                'price' => 909800,
                'sort' => 10,
            ],
            [
                'model_id' => 1,
                'type_id' => 2,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '98 л.с.',
                'transmission' => '4AT',
                'title' => 'Comfort',
                'price' => 955500,
                'sort' => 11,
            ],
            [
                'model_id' => 1,
                'type_id' => 2,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '98 л.с.',
                'transmission' => '4AT',
                'title' => 'Luxe',
                'price' => 1004800,
                'sort' => 12,
            ],
            // hatchback
            [
                'model_id' => 1,
                'type_id' => 6,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5МТ',
                'title' => 'Classic',
                'price' => 778500,
                'sort' => 1,
            ],
            [
                'model_id' => 1,
                'type_id' => 6,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort Light',
                'price' => 825500,
                'sort' => 2,
            ],
            [
                'model_id' => 1,
                'type_id' => 6,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort',
                'price' => 832500,
                'sort' => 3,
            ],
            [
                'model_id' => 1,
                'type_id' => 6,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '98 л.с.',
                'transmission' => '4AТ',
                'title' => 'Comfort',
                'price' => 952500,
                'sort' => 4,
            ],
            [
                'model_id' => 1,
                'type_id' => 6,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '98 л.с.',
                'transmission' => '4AТ',
                'title' => 'Luxe',
                'price' => 1001800,
                'sort' => 5,
            ],
            // universal
            [
                'model_id' => 1,
                'type_id' => 3,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Classic\'22',
                'price' => 705300,
                'sort' => 1,
            ],
            [
                'model_id' => 1,
                'type_id' => 3,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Classic',
                'price' => 785500,
                'sort' => 2,
            ],
            [
                'model_id' => 1,
                'type_id' => 3,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Comfort Light',
                'price' => 832500,
                'sort' => 3,
            ],
            [
                'model_id' => 1,
                'type_id' => 3,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5MT',
                'title' => 'Comfort',
                'price' => 839500,
                'sort' => 4,
            ],
            [
                'model_id' => 1,
                'type_id' => 3,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5MT',
                'title' => 'Comfort',
                'price' => 864500,
                'sort' => 5,
            ],
            [
                'model_id' => 1,
                'type_id' => 3,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5MT',
                'title' => 'Luxe',
                'price' => 913800,
                'sort' => 6,
            ],
            [
                'model_id' => 1,
                'type_id' => 3,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '98 л.с.',
                'transmission' => '4AT',
                'title' => 'Comfort',
                'price' => 959500,
                'sort' => 7,
            ],
            [
                'model_id' => 1,
                'type_id' => 3,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '98 л.с.',
                'transmission' => '4AT',
                'title' => 'Luxe',
                'price' => 1008800,
                'sort' => 8,
            ],
            // drive_active
            [
                'model_id' => 1,
                'type_id' => 5,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort Light',
                'price' => 940900,
                'sort' => 1,
            ],
            [
                'model_id' => 1,
                'type_id' => 5,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort',
                'price' => 947900,
                'sort' => 2,
            ],
        ];

        $vesta = [
            // Vesta sedan
            [
                'model_id' => 2,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Classic',
                'price' => 1121900,
                'sort' => 1,
            ],
            [
                'model_id' => 2,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort Light',
                'price' => 1171900,
                'sort' => 2,
            ],
            [
                'model_id' => 2,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort',
                'price' => 1182900,
                'sort' => 3,
            ],
            [
                'model_id' => 2,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe EnjoY',
                'price' => 1286900,
                'sort' => 4,
            ],
            [
                'model_id' => 2,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe EnjoY Pro',
                'price' => 1305900,
                'sort' => 5,
            ],
            [
                'model_id' => 2,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Exclusive',
                'price' => 1361900,
                'sort' => 6,
            ],
            [
                'model_id' => 2,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '113 л.с.',
                'transmission' => 'АТ',
                'title' => 'Comfort Light',
                'price' => 1316900,
                'sort' => 7,
            ],
            [
                'model_id' => 2,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '113 л.с.',
                'transmission' => 'АТ',
                'title' => 'Comfort',
                'price' => 1327900,
                'sort' => 8,
            ],
            [
                'model_id' => 2,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '113 л.с.',
                'transmission' => 'АТ',
                'title' => 'Luxe EnjoY Pro',
                'price' => 1450900,
                'sort' => 9,
            ],
            [
                'model_id' => 2,
                'type_id' => 1,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '113 л.с.',
                'transmission' => 'АТ',
                'title' => 'Exclusive',
                'price' => 1506900,
                'sort' => 10,
            ],
            // Vesta Cross
            [
                'model_id' => 2,
                'type_id' => 4,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort',
                'price' => 1269900,
                'sort' => 1,
            ],
            [
                'model_id' => 2,
                'type_id' => 4,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => '[BLACK]',
                'price' => 1304900,
                'sort' => 2,
            ],
            [
                'model_id' => 2,
                'type_id' => 4,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe EnjoY',
                'price' => 1361900,
                'sort' => 3,
            ],
            [
                'model_id' => 2,
                'type_id' => 4,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe EnjoY Pro',
                'price' => 1380900,
                'sort' => 4,
            ],
            [
                'model_id' => 2,
                'type_id' => 4,
                'engine' => '1,8 л',
                'flap' => '16-кл.',
                'capacity' => '122 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort',
                'price' => 1299900,
                'sort' => 5,
            ],
            [
                'model_id' => 2,
                'type_id' => 4,
                'engine' => '1,8 л',
                'flap' => '16-кл.',
                'capacity' => '122 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe EnjoY Pro',
                'price' => 1410900,
                'sort' => 6,
            ],
            [
                'model_id' => 2,
                'type_id' => 4,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '113 л.с.',
                'transmission' => 'АТ',
                'title' => 'Comfort',
                'price' => 1404900,
                'sort' => 7,
            ],
            [
                'model_id' => 2,
                'type_id' => 4,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '113 л.с.',
                'transmission' => 'АТ',
                'title' => '[BLACK]',
                'price' => 1439900,
                'sort' => 8,
            ],
            [
                'model_id' => 2,
                'type_id' => 4,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '113 л.с.',
                'transmission' => 'АТ',
                'title' => 'Luxe EnjoY Pro',
                'price' => 1515900,
                'sort' => 9,
            ],
            // Vesta SW
            [
                'model_id' => 2,
                'type_id' => 7,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Classic Start',
                'price' => 1213900,
                'sort' => 1,
            ],
            [
                'model_id' => 2,
                'type_id' => 7,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort Light',
                'price' => 1230900,
                'sort' => 2,
            ],
            [
                'model_id' => 2,
                'type_id' => 7,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort',
                'price' => 1241900,
                'sort' => 3,
            ],
            [
                'model_id' => 2,
                'type_id' => 7,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe EnjoY',
                'price' => 1348900,
                'sort' => 4,
            ],
            [
                'model_id' => 2,
                'type_id' => 7,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe EnjoY Pro',
                'price' => 1367900,
                'sort' => 5,
            ],
            [
                'model_id' => 2,
                'type_id' => 7,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Exclusive',
                'price' => 1423900,
                'sort' => 6,
            ],
            [
                'model_id' => 2,
                'type_id' => 7,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '113 л.с.',
                'transmission' => 'АТ',
                'title' => 'Comfort Light',
                'price' => 1375900,
                'sort' => 7,
            ],
            [
                'model_id' => 2,
                'type_id' => 7,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '113 л.с.',
                'transmission' => 'АТ',
                'title' => 'Comfort',
                'price' => 1386900,
                'sort' => 8,
            ],
            [
                'model_id' => 2,
                'type_id' => 7,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '113 л.с.',
                'transmission' => 'АТ',
                'title' => 'Luxe EnjoY Pro',
                'price' => 1512900,
                'sort' => 9,
            ],
            [
                'model_id' => 2,
                'type_id' => 7,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '113 л.с.',
                'transmission' => 'АТ',
                'title' => 'Exclusive',
                'price' => 1568900,
                'sort' => 10,
            ],
            // Vesta SW Cross
            [
                'model_id' => 2,
                'type_id' => 8,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort',
                'price' => 1328900,
                'sort' => 1,
            ],
            [
                'model_id' => 2,
                'type_id' => 8,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => '[BLACK]',
                'price' => 1363900,
                'sort' => 2,
            ],
            [
                'model_id' => 2,
                'type_id' => 8,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe EnjoY ',
                'price' => 1423900,
                'sort' => 3,
            ],
            [
                'model_id' => 2,
                'type_id' => 8,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe EnjoY Pro',
                'price' => 1442900,
                'sort' => 4,
            ],
            [
                'model_id' => 2,
                'type_id' => 8,
                'engine' => '1,8 л',
                'flap' => '16-кл.',
                'capacity' => '122 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort',
                'price' => 1358900,
                'sort' => 5,
            ],
            [
                'model_id' => 2,
                'type_id' => 8,
                'engine' => '1,8 л',
                'flap' => '16-кл.',
                'capacity' => '122 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe EnjoY Pro',
                'price' => 1472900,
                'sort' => 6,
            ],
            [
                'model_id' => 2,
                'type_id' => 8,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '113 л.с.',
                'transmission' => 'АТ',
                'title' => 'Comfort',
                'price' => 1463900,
                'sort' => 7,
            ],
            [
                'model_id' => 2,
                'type_id' => 8,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '113 л.с.',
                'transmission' => 'АТ',
                'title' => '[BLACK]',
                'price' => 1498900,
                'sort' => 8,
            ],
            [
                'model_id' => 2,
                'type_id' => 8,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '113 л.с.',
                'transmission' => 'АТ',
                'title' => 'Luxe EnjoY Pro',
                'price' => 1577900,
                'sort' => 9,
            ],
            // Vesta CNG
            [
                'model_id' => 2,
                'type_id' => 9,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => NULL,
                'transmission' => '5МТ',
                'title' => 'Classic Start',
                'price' => 1030900,
                'sort' => 1,
            ],
            [
                'model_id' => 2,
                'type_id' => 9,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => NULL,
                'transmission' => '5МТ',
                'title' => 'Comfort',
                'price' => 1061900,
                'sort' => 2,
            ],
            [
                'model_id' => 2,
                'type_id' => 9,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => NULL,
                'transmission' => '5МТ',
                'title' => 'Luxe EnjoY',
                'price' => 1156900,
                'sort' => 3,
            ],
            // Vesta Sport
            [
                'model_id' => 2,
                'type_id' => 10,
                'engine' => '1,8 л',
                'flap' => '16-кл.',
                'capacity' => '145 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe',
                'price' => 1597900,
                'sort' => 1,
            ],
            [
                'model_id' => 2,
                'type_id' => 10,
                'engine' => '1,8 л',
                'flap' => '16-кл.',
                'capacity' => '145 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe EnjoY Pro',
                'price' => 1653900,
                'sort' => 2,
            ],
            // Xray
            [
                'model_id' => 3,
                'type_id' => 20,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Standard',
                'price' => 1106900,
                'sort' => 1,
            ],
            [
                'model_id' => 3,
                'type_id' => 20,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Classic Air conditioner',
                'price' => 1136900,
                'sort' => 2,
            ],
            [
                'model_id' => 3,
                'type_id' => 20,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort Light',
                'price' => 1161900,
                'sort' => 3,
            ],
            [
                'model_id' => 3,
                'type_id' => 20,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort',
                'price' => 1169900,
                'sort' => 4,
            ],
            [
                'model_id' => 3,
                'type_id' => 20,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => '#CLUB',
                'price' => 1194900,
                'sort' => 5,
            ],
            [
                'model_id' => 3,
                'type_id' => 20,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => '#CLUB EnjoY',
                'price' => 1223900,
                'sort' => 6,
            ],
            [
                'model_id' => 3,
                'type_id' => 20,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe',
                'price' => 1250900,
                'sort' => 7,
            ],
            [
                'model_id' => 3,
                'type_id' => 20,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5AМТ',
                'title' => 'Comfort Light',
                'price' => 1191900,
                'sort' => 8,
            ],
            [
                'model_id' => 3,
                'type_id' => 20,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5AМТ',
                'title' => 'Comfort',
                'price' => 1199900,
                'sort' => 9,
            ],
            [
                'model_id' => 3,
                'type_id' => 20,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5AМТ',
                'title' => '#CLUB',
                'price' => 1224900,
                'sort' => 10,
            ],
            [
                'model_id' => 3,
                'type_id' => 20,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5AМТ',
                'title' => '#CLUB EnjoY',
                'price' => 1253900,
                'sort' => 11,
            ],
            [
                'model_id' => 3,
                'type_id' => 20,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5AМТ',
                'title' => 'Luxe Prestige',
                'price' => 1307900,
                'sort' => 12,
            ],
            // Xray Cross
            [
                'model_id' => 3,
                'type_id' => 4,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Classic',
                'price' => 1249900,
                'sort' => 1,
            ],
            [
                'model_id' => 3,
                'type_id' => 4,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort Light',
                'price' => 1338900,
                'sort' => 2,
            ],
            [
                'model_id' => 3,
                'type_id' => 4,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort',
                'price' => 1346900,
                'sort' => 3,
            ],
            [
                'model_id' => 3,
                'type_id' => 4,
                'engine' => '1,8 л',
                'flap' => '16-кл.',
                'capacity' => '122 л.с.',
                'transmission' => '5МТ',
                'title' => '[BLACK]',
                'price' => 1444900,
                'sort' => 4,
            ],
            [
                'model_id' => 3,
                'type_id' => 4,
                'engine' => '1,8 л',
                'flap' => '16-кл.',
                'capacity' => '122 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe',
                'price' => 1466900,
                'sort' => 5,
            ],
            [
                'model_id' => 3,
                'type_id' => 4,
                'engine' => '1,8 л',
                'flap' => '16-кл.',
                'capacity' => '122 л.с.',
                'transmission' => '5МТ',
                'title' => 'Instinct',
                'price' => 1516900,
                'sort' => 6,
            ],
            [
                'model_id' => 3,
                'type_id' => 4,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '113 л.с.',
                'transmission' => 'AT',
                'title' => 'Classic Optima',
                'price' => 1441900,
                'sort' => 7,
            ],
            [
                'model_id' => 3,
                'type_id' => 4,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '113 л.с.',
                'transmission' => 'AT',
                'title' => 'Comfort Light',
                'price' => 1493900,
                'sort' => 8,
            ],
            [
                'model_id' => 3,
                'type_id' => 4,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '113 л.с.',
                'transmission' => 'AT',
                'title' => 'Comfort',
                'price' => 1501900,
                'sort' => 9,
            ],
            [
                'model_id' => 3,
                'type_id' => 4,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '113 л.с.',
                'transmission' => 'AT',
                'title' => '[BLACK]',
                'price' => 1549900,
                'sort' => 10,
            ],
            [
                'model_id' => 3,
                'type_id' => 4,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '113 л.с.',
                'transmission' => 'AT',
                'title' => 'Luxe',
                'price' => 1571900,
                'sort' => 11,
            ],
            [
                'model_id' => 3,
                'type_id' => 4,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '113 л.с.',
                'transmission' => 'AT',
                'title' => 'Instinct',
                'price' => 1621900,
                'sort' => 12,
            ],
            // Largus Universal
            [
                'model_id' => 5,
                'type_id' => 3,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5МТ',
                'title' => 'Classic',
                'price' => 1235900,
                'sort' => 1,
            ],
            [
                'model_id' => 5,
                'type_id' => 3,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort Light',
                'price' => 1303900,
                'sort' => 2,
            ],
            [
                'model_id' => 5,
                'type_id' => 3,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort',
                'price' => 1312900,
                'sort' => 3,
            ],
            [
                'model_id' => 5,
                'type_id' => 3,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort Light',
                'price' => 1323900,
                'sort' => 4,
            ],
            [
                'model_id' => 5,
                'type_id' => 3,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort',
                'price' => 1332900,
                'sort' => 5,
            ],
            [
                'model_id' => 5,
                'type_id' => 3,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe Light',
                'price' => 1386900,
                'sort' => 7,
            ],
            [
                'model_id' => 5,
                'type_id' => 3,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe',
                'price' => 1406900,
                'sort' => 8,
            ],
            // Largus Cross
            [
                'model_id' => 5,
                'type_id' => 4,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort',
                'price' => 1377900,
                'sort' => 1,
            ],
            [
                'model_id' => 5,
                'type_id' => 4,
                'engine' => '1,6 л',
                'flap' => '8-кл.',
                'capacity' => '90 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort Light',
                'price' => 1378900,
                'sort' => 2,
            ],
            [
                'model_id' => 5,
                'type_id' => 4,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort',
                'price' => 1387900,
                'sort' => 3,
            ],
            [
                'model_id' => 5,
                'type_id' => 4,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe Light',
                'price' => 1426900,
                'sort' => 4,
            ],
            [
                'model_id' => 5,
                'type_id' => 4,
                'engine' => '1,6 л',
                'flap' => '16-кл.',
                'capacity' => '106 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe',
                'price' => 1446900,
                'sort' => 5,
            ],
        ];

        $niva_travel = [
            [
                'model_id' => 6,
                'type_id' => 24,
                'engine' => '1,7 л',
                'flap' => '8-кл.',
                'capacity' => '80 л.с.',
                'transmission' => '5МТ',
                'title' => 'Classic',
                'price' => 1066900,
                'sort' => 1,
            ],
            [
                'model_id' => 6,
                'type_id' => 24,
                'engine' => '1,7 л',
                'flap' => '8-кл.',
                'capacity' => '80 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort',
                'price' => 1123900,
                'sort' => 2,
            ],
            [
                'model_id' => 6,
                'type_id' => 24,
                'engine' => '1,7 л',
                'flap' => '8-кл.',
                'capacity' => '80 л.с.',
                'transmission' => '5МТ',
                'title' => '[BLACK]',
                'price' => 1159900,
                'sort' => 3,
            ],
            [
                'model_id' => 6,
                'type_id' => 24,
                'engine' => '1,7 л',
                'flap' => '8-кл.',
                'capacity' => '80 л.с.',
                'transmission' => '5МТ',
                'title' => 'Comfort Off-road',
                'price' => 1171900,
                'sort' => 3,
            ],
            [
                'model_id' => 6,
                'type_id' => 24,
                'engine' => '1,7 л',
                'flap' => '8-кл.',
                'capacity' => '80 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe',
                'price' => 1209900,
                'sort' => 4,
            ],
            [
                'model_id' => 6,
                'type_id' => 24,
                'engine' => '1,7 л',
                'flap' => '8-кл.',
                'capacity' => '80 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe Off-road',
                'price' => 1232900,
                'sort' => 5,
            ],
        ];

        // Niva legend
        $niva_legend = [
            // Three doors
            [
                'model_id' => 7,
                'type_id' => 11,
                'engine' => '1,7 л',
                'flap' => '8-кл.',
                'capacity' => '83 л.с.',
                'transmission' => '5МТ',
                'title' => 'Classic',
                'price' => 818900,
                'sort' => 1,
            ],
            [
                'model_id' => 7,
                'type_id' => 11,
                'engine' => '1,7 л',
                'flap' => '8-кл.',
                'capacity' => '83 л.с.',
                'transmission' => '5МТ',
                'title' => '[BLACK]',
                'price' => 898900,
                'sort' => 2,
            ],
            [
                'model_id' => 7,
                'type_id' => 11,
                'engine' => '1,7 л',
                'flap' => '8-кл.',
                'capacity' => '83 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe',
                'price' => 835900,
                'sort' => 3,
            ],
            [
                'model_id' => 7,
                'type_id' => 11,
                'engine' => '1,7 л',
                'flap' => '8-кл.',
                'capacity' => '83 л.с.',
                'transmission' => '5МТ',
                'title' => 'Urban',
                'price' => 889900,
                'sort' => 4,
            ],
            // Five doors
            [
                'model_id' => 7,
                'type_id' => 13,
                'engine' => '1,7 л',
                'flap' => '8-кл.',
                'capacity' => '83 л.с.',
                'transmission' => '5МТ',
                'title' => 'Classic',
                'price' => 918900,
                'sort' => 1,
            ],
            [
                'model_id' => 7,
                'type_id' => 13,
                'engine' => '1,7 л',
                'flap' => '8-кл.',
                'capacity' => '83 л.с.',
                'transmission' => '5МТ',
                'title' => '[BLACK]',
                'price' => 998900,
                'sort' => 2,
            ],
            [
                'model_id' => 7,
                'type_id' => 13,
                'engine' => '1,7 л',
                'flap' => '8-кл.',
                'capacity' => '83 л.с.',
                'transmission' => '5МТ',
                'title' => 'Luxe',
                'price' => 935900,
                'sort' => 3,
            ],
            [
                'model_id' => 7,
                'type_id' => 13,
                'engine' => '1,7 л',
                'flap' => '8-кл.',
                'capacity' => '83 л.с.',
                'transmission' => '5МТ',
                'title' => 'Urban',
                'price' => 989900,
                'sort' => 4,
            ],
        ];

        $complectations = array_merge($granta, $vesta, $niva_travel, $niva_legend);
        DB::table('complectations')->insert($complectations);
    }
}
