<?php

use Illuminate\Database\Seeder;

class FeaturesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $granta = [
            // Granta drive_active
            [
                'model_id' => 1,
                'type_id' => 5,
                'name' => 'Седан',
                'title' => 'Кузов',
                'icon' => 'body',
            ],
            [
                'model_id' => 1,
                'type_id' => 5,
                'name' => 'Передний',
                'title' => 'Привод',
                'icon' => 'drive',
            ],
            [
                'model_id' => 1,
                'type_id' => 5,
                'name' => '1.6 л',
                'title' => 'объём двигателя',
                'icon' => 'engine',
            ],
            [
                'model_id' => 1,
                'type_id' => 5,
                'name' => 'МТ',
                'title' => 'коробка двигателя',
                'icon' => 'transmission',
            ],
            [
                'model_id' => 1,
                'type_id' => 5,
                'name' => '5',
                'title' => 'места',
                'icon' => 'seats',
            ],
            [
                'model_id' => 1,
                'type_id' => 5,
                'name' => 'Бензин',
                'title' => 'топливо',
                'icon' => 'fuel_type',
            ],
            [
                'model_id' => 1,
                'type_id' => 5,
                'name' => 'от 5,2л / 100км',
                'title' => 'расход топлива',
                'icon' => 'fuel',
            ],
            [
                'model_id' => 1,
                'type_id' => 5,
                'name' => 'до 184 км/ч',
                'title' => 'макс. скорост',
                'icon' => 'speed',
            ],
            // Granta Hatchback
            [
                'model_id' => 1,
                'type_id' => 6,
                'name' => 'Хэтчбек',
                'title' => 'Кузов',
                'icon' => 'body',
            ],
            [
                'model_id' => 1,
                'type_id' => 6,
                'name' => 'Передний',
                'title' => 'Привод',
                'icon' => 'drive',
            ],
            [
                'model_id' => 1,
                'type_id' => 6,
                'name' => '1.6 л',
                'title' => 'объём двигател',
                'icon' => 'engine',
            ],
            [
                'model_id' => 1,
                'type_id' => 6,
                'name' => 'MT / AT',
                'title' => 'коробка двигателя',
                'icon' => 'transmission',
            ],
            [
                'model_id' => 1,
                'type_id' => 6,
                'name' => '5',
                'title' => 'места',
                'icon' => 'seats',
            ],
            [
                'model_id' => 1,
                'type_id' => 6,
                'name' => 'Бензин',
                'title' => 'топливо',
                'icon' => 'fuel_type',
            ],
            [
                'model_id' => 1,
                'type_id' => 6,
                'name' => 'от 5,3л / 100к',
                'title' => 'расход топлив',
                'icon' => 'fuel',
            ],
            [
                'model_id' => 1,
                'type_id' => 6,
                'name' => 'до 176 км/ч',
                'title' => 'макс. скорость',
                'icon' => 'speed',
            ],
            // Granta Liftback
            [
                'model_id' => 1,
                'type_id' => 2,
                'name' => 'Лифтбек',
                'title' => 'Кузов',
                'icon' => 'body',
            ],
            [
                'model_id' => 1,
                'type_id' => 2,
                'name' => 'Передний',
                'title' => 'Привод',
                'icon' => 'drive',
            ],
            [
                'model_id' => 1,
                'type_id' => 2,
                'name' => '1.6 л',
                'title' => 'объём двигателя',
                'icon' => 'engine',
            ],
            [
                'model_id' => 1,
                'type_id' => 2,
                'name' => 'MT / AT',
                'title' => 'коробка двигателя',
                'icon' => 'transmission',
            ],
            [
                'model_id' => 1,
                'type_id' => 2,
                'name' => '5',
                'title' => 'места',
                'icon' => 'seats',
            ],
            [
                'model_id' => 1,
                'type_id' => 2,
                'name' => 'Бензин',
                'title' => 'топливо',
                'icon' => 'fuel_type',
            ],
            [
                'model_id' => 1,
                'type_id' => 2,
                'name' => 'от 5,2л / 100км',
                'title' => 'расход топлив',
                'icon' => 'fuel',
            ],
            [
                'model_id' => 1,
                'type_id' => 2,
                'name' => 'до 183 км/ч',
                'title' => 'макс. скорость',
                'icon' => 'speed',
            ],
            // Granta Sedan
            [
                'model_id' => 1,
                'type_id' => 1,
                'name' => 'Седан',
                'title' => 'Кузов',
                'icon' => 'body',
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'name' => 'Передний',
                'title' => 'Привод',
                'icon' => 'drive',
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'name' => '1.6 л',
                'title' => 'объём двигателя',
                'icon' => 'engine',
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'name' => 'MT / AT',
                'title' => 'коробка двигателя',
                'icon' => 'transmission',
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'name' => '5',
                'title' => 'места',
                'icon' => 'seats',
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'name' => 'Бензин',
                'title' => 'топливо',
                'icon' => 'fuel_type',
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'name' => 'от 5,2л / 100км',
                'title' => 'расход топлива',
                'icon' => 'fuel',
            ],
            [
                'model_id' => 1,
                'type_id' => 1,
                'name' => 'до 184 км/ч',
                'title' => 'макс. скорость',
                'icon' => 'speed',
            ],
            // Granta Universal
            [
                'model_id' => 1,
                'type_id' => 3,
                'name' => 'Универсал',
                'title' => 'Кузов',
                'icon' => 'body',
            ],
            [
                'model_id' => 1,
                'type_id' => 3,
                'name' => 'Передний',
                'title' => 'Привод',
                'icon' => 'drive',
            ],
            [
                'model_id' => 1,
                'type_id' => 3,
                'name' => '1.6 л',
                'title' => 'объём двигателя',
                'icon' => 'engine',
            ],
            [
                'model_id' => 1,
                'type_id' => 3,
                'name' => 'MT / AT',
                'title' => 'коробка двигателя',
                'icon' => 'transmission',
            ],
            [
                'model_id' => 1,
                'type_id' => 3,
                'name' => '5',
                'title' => 'места',
                'icon' => 'seats',
            ],
            [
                'model_id' => 1,
                'type_id' => 3,
                'name' => 'Бензин',
                'title' => 'топливо',
                'icon' => 'fuel_type',
            ],
            [
                'model_id' => 1,
                'type_id' => 3,
                'name' => 'от 5,2л / 100км',
                'title' => 'расход топлива',
                'icon' => 'fuel',
            ],
            [
                'model_id' => 1,
                'type_id' => 3,
                'name' => 'до 182 км/',
                'title' => 'макс. скорост',
                'icon' => 'speed',
            ],
        ];

        $vesta = [
            // Vesta Sedan
            [
                'model_id' => 2,
                'type_id' => 1,
                'name' => 'Cедан',
                'title' => 'Кузов',
                'icon' => 'body',
            ],
            [
                'model_id' => 2,
                'type_id' => 1,
                'name' => 'Передний',
                'title' => 'Привод',
                'icon' => 'drive',
            ],
            [
                'model_id' => 2,
                'type_id' => 1,
                'name' => '1.6 л',
                'title' => 'объём двигателя',
                'icon' => 'engine',
            ],
            [
                'model_id' => 2,
                'type_id' => 1,
                'name' => 'MT / AT',
                'title' => 'коробка двигателя',
                'icon' => 'transmission',
            ],
            [
                'model_id' => 2,
                'type_id' => 1,
                'name' => '5',
                'title' => 'места',
                'icon' => 'seats',
            ],
            [
                'model_id' => 2,
                'type_id' => 1,
                'name' => 'Бензин',
                'title' => 'топливо',
                'icon' => 'fuel_type',
            ],
            [
                'model_id' => 2,
                'type_id' => 1,
                'name' => 'от 5,5л / 100км',
                'title' => 'расход топлива',
                'icon' => 'fuel',
            ],
            [
                'model_id' => 2,
                'type_id' => 1,
                'name' => 'до 182 км/',
                'title' => 'макс. скорост',
                'icon' => 'speed',
            ],
            // Vesta Cross
            [
                'model_id' => 2,
                'type_id' => 4,
                'name' => 'Cедан',
                'title' => 'Кузов',
                'icon' => 'body',
            ],
            [
                'model_id' => 2,
                'type_id' => 4,
                'name' => 'Передний',
                'title' => 'Привод',
                'icon' => 'drive',
            ],
            [
                'model_id' => 2,
                'type_id' => 4,
                'name' => '1.6 л',
                'title' => 'объём двигателя',
                'icon' => 'engine',
            ],
            [
                'model_id' => 2,
                'type_id' => 4,
                'name' => 'MT / AT',
                'title' => 'коробка двигателя',
                'icon' => 'transmission',
            ],
            [
                'model_id' => 2,
                'type_id' => 4,
                'name' => '5',
                'title' => 'места',
                'icon' => 'seats',
            ],
            [
                'model_id' => 2,
                'type_id' => 4,
                'name' => 'Бензин',
                'title' => 'топливо',
                'icon' => 'fuel_type',
            ],
            [
                'model_id' => 2,
                'type_id' => 4,
                'name' => 'от 5,9л / 100км',
                'title' => 'расход топлива',
                'icon' => 'fuel',
            ],
            [
                'model_id' => 2,
                'type_id' => 4,
                'name' => 'до 180 км/',
                'title' => 'макс. скорост',
                'icon' => 'speed',
            ],
            // Vesta SW
            [
                'model_id' => 2,
                'type_id' => 7,
                'name' => 'Универсал',
                'title' => 'Кузов',
                'icon' => 'body',
            ],
            [
                'model_id' => 2,
                'type_id' => 7,
                'name' => 'Передний',
                'title' => 'Привод',
                'icon' => 'drive',
            ],
            [
                'model_id' => 2,
                'type_id' => 7,
                'name' => '1.6 л',
                'title' => 'объём двигателя',
                'icon' => 'engine',
            ],
            [
                'model_id' => 2,
                'type_id' => 7,
                'name' => 'MT / AT',
                'title' => 'коробка двигателя',
                'icon' => 'transmission',
            ],
            [
                'model_id' => 2,
                'type_id' => 7,
                'name' => '5',
                'title' => 'места',
                'icon' => 'seats',
            ],
            [
                'model_id' => 2,
                'type_id' => 7,
                'name' => 'Бензин',
                'title' => 'топливо',
                'icon' => 'fuel_type',
            ],
            [
                'model_id' => 2,
                'type_id' => 7,
                'name' => 'от 5,9л / 100км',
                'title' => 'расход топлива',
                'icon' => 'fuel',
            ],
            [
                'model_id' => 2,
                'type_id' => 7,
                'name' => 'до 178 км/',
                'title' => 'макс. скорост',
                'icon' => 'speed',
            ],
            // Vesta SW Cross
            [
                'model_id' => 2,
                'type_id' => 8,
                'name' => 'Универсал',
                'title' => 'Кузов',
                'icon' => 'body',
            ],
            [
                'model_id' => 2,
                'type_id' => 8,
                'name' => 'Передний',
                'title' => 'Привод',
                'icon' => 'drive',
            ],
            [
                'model_id' => 2,
                'type_id' => 8,
                'name' => '1.6 л',
                'title' => 'объём двигателя',
                'icon' => 'engine',
            ],
            [
                'model_id' => 2,
                'type_id' => 8,
                'name' => 'MT / AT',
                'title' => 'коробка двигателя',
                'icon' => 'transmission',
            ],
            [
                'model_id' => 2,
                'type_id' => 8,
                'name' => '5',
                'title' => 'места',
                'icon' => 'seats',
            ],
            [
                'model_id' => 2,
                'type_id' => 8,
                'name' => 'Бензин',
                'title' => 'топливо',
                'icon' => 'fuel_type',
            ],
            [
                'model_id' => 2,
                'type_id' => 8,
                'name' => 'от 6л / 100км',
                'title' => 'расход топлива',
                'icon' => 'fuel',
            ],
            [
                'model_id' => 2,
                'type_id' => 8,
                'name' => 'до 180 км/',
                'title' => 'макс. скорост',
                'icon' => 'speed',
            ],
            // Vesta CNG
            [
                'model_id' => 2,
                'type_id' => 9,
                'name' => 'Седан',
                'title' => 'Кузов',
                'icon' => 'body',
            ],
            [
                'model_id' => 2,
                'type_id' => 9,
                'name' => 'Передний',
                'title' => 'Привод',
                'icon' => 'drive',
            ],
            [
                'model_id' => 2,
                'type_id' => 9,
                'name' => '1.6 л',
                'title' => 'объём двигателя',
                'icon' => 'engine',
            ],
            [
                'model_id' => 2,
                'type_id' => 9,
                'name' => 'CNG / AT',
                'title' => 'коробка двигателя',
                'icon' => 'transmission',
            ],
            [
                'model_id' => 2,
                'type_id' => 9,
                'name' => '5',
                'title' => 'места',
                'icon' => 'seats',
            ],
            [
                'model_id' => 2,
                'type_id' => 9,
                'name' => 'Двухтопливный',
                'title' => 'топливо',
                'icon' => 'fuel_type',
            ],
            [
                'model_id' => 2,
                'type_id' => 9,
                'name' => 'от 5,2л / 100км',
                'title' => 'расход топлива',
                'icon' => 'fuel',
            ],
            [
                'model_id' => 2,
                'type_id' => 9,
                'name' => 'до 175 км/',
                'title' => 'макс. скорост',
                'icon' => 'speed',
            ],
            // Vesta Sport
            [
                'model_id' => 2,
                'type_id' => 10,
                'name' => 'Седан',
                'title' => 'Кузов',
                'icon' => 'body',
            ],
            [
                'model_id' => 2,
                'type_id' => 10,
                'name' => 'Передний',
                'title' => 'Привод',
                'icon' => 'drive',
            ],
            [
                'model_id' => 2,
                'type_id' => 10,
                'name' => '1.8 л',
                'title' => 'объём двигателя',
                'icon' => 'engine',
            ],
            [
                'model_id' => 2,
                'type_id' => 10,
                'name' => 'MT',
                'title' => 'коробка двигателя',
                'icon' => 'transmission',
            ],
            [
                'model_id' => 2,
                'type_id' => 10,
                'name' => '5',
                'title' => 'места',
                'icon' => 'seats',
            ],
            [
                'model_id' => 2,
                'type_id' => 10,
                'name' => 'Бензин',
                'title' => 'топливо',
                'icon' => 'fuel_type',
            ],
            [
                'model_id' => 2,
                'type_id' => 10,
                'name' => 'от 6,4л / 100км',
                'title' => 'расход топлива',
                'icon' => 'fuel',
            ],
            [
                'model_id' => 2,
                'type_id' => 9,
                'name' => 'до 193 км/',
                'title' => 'макс. скорост',
                'icon' => 'speed',
            ],
        ];

        $features = array_merge($granta, $vesta);
        DB::table('features')->insert($features);
    }
}
